# Your Solution

services:

  book_catalog:
    image: book_catalog
    build: 
      context: ./book_catalog
      dockerfile: Dockerfile
    container_name: book_catalog
    ports:
     - "3000:3000"
    environment:
      - PORT=3000
      - DATABASE_URL=postgresql://ashwathi_user:LAeoP0BXF4eCzTESXxCh7Dj0cni0ZH4c@dpg-crts4652ng1s73ce8u80-a.oregon-postgres.render.com/ashwathi

  inventory_management:
    image: inventory_management
    build: 
      context: ./inventory_management
      dockerfile: Dockerfile
    container_name: inventory_management
    ports:
     - "5000:5000"
    environment:
      - PORT=5000
      - DATABASE_URL=postgresql://ashwathi_user:LAeoP0BXF4eCzTESXxCh7Dj0cni0ZH4c@dpg-crts4652ng1s73ce8u80-a.oregon-postgres.render.com/ashwathi