# Your Solution

services:

  book_catalog:
    image: book_catalog
    build: 
      context: ./book_catalog
      dockerfile: Dockerfile
    container_name: book_catalog
    ports:
     - "3000:3000"
    environment:
      - PORT=3000
      - DATABASE_URL=postgresql://renu:g1S5lGnzjpOe2VmezYm9333vxtultjze@dpg-crr29flds78s73cpgm7g-a.oregon-postgres.render.com/week7_1s7d

  inventory_management:
    image: inventory_management
    build: 
      context: ./inventory_management
      dockerfile: Dockerfile
    container_name: inventory_management
    ports:
     - "5000:5000"
    environment:
      - PORT=5000
      - DATABASE_URL=postgresql://renu:g1S5lGnzjpOe2VmezYm9333vxtultjze@dpg-crr29flds78s73cpgm7g-a.oregon-postgres.render.com/week7_1s7d